data:
  batch_size: 1
  cache_dir: /tmp/monai-cache
  data_dir: prostate158
  dataset_type: persistent
  image_cols:
  - t2
  - adc
  - dwi
  label_cols:
  - adc_tumor_reader1
  test: false
  test_csv: prostate158/test.csv
  train: true
  train_csv: prostate158/train.csv
  valid: true
  valid_csv: prostate158/valid.csv
debug: false
device: cuda
log_dir: tumor_1/logs
loss:
  DiceFocalLoss:
    include_background: false
    softmax: true
    to_onehot_y: true
lr_scheduler:
  OneCycleLR:
    max_lr: 0.001
model:
  act: PRELU
  channels:
  - 16
  - 32
  - 64
  - 128
  - 256
  - 512
  dropout: 0.15
  norm: BATCH
  num_res_units: 4
  out_channels: 2
  strides:
  - 2
  - 2
  - 2
  - 2
  - 2
model_dir: models
ndim: 3
optimizer:
  Novograd:
    amsgrad: true
    lr: 0.001
    weight_decay: 0.01
out_dir: tumor_1/output
overwrite: false
run_id: tumor_1
seed: 42
training:
  early_stopping_patience: 1000
  max_epochs: 10
transforms:
  adjust_contrast:
    gamma: 2.0
  gaussian_noise:
    mean: 0.1
    std: 0.25
  gaussian_sharpen:
    alpha:
    - 10.0
    - 30.0
    sigma1_x:
    - 0.5
    - 1.0
    sigma1_y:
    - 0.5
    - 1.0
    sigma1_z:
    - 0.5
    - 1.0
    sigma2_x:
    - 0.5
    - 1.0
    sigma2_y:
    - 0.5
    - 1.0
    sigma2_z:
    - 0.5
    - 1.0
  mode:
  - bilinear
  - bilinear
  - bilinear
  - nearest
  orientation: RAS
  prob: 0.175
  rand_affine:
    rotate_range: 5
    shear_range: 0.5
    translate_range: 25
  rand_bias_field:
    coeff_range:
    - 0.0
    - 0.01
    degree: 10
  rand_elastic:
    magnitude_range:
    - 0.5
    - 1.5
    rotate_range: 5
    shear_range: 0.5
    sigma_range:
    - 0.5
    - 1.5
    translate_range: 25
  rand_gaussian_smooth:
    sigma_x:
    - 0.25
    - 1.5
    sigma_y:
    - 0.25
    - 1.5
    sigma_z:
    - 0.25
    - 1.5
  rand_gibbs_nose:
    alpha:
    - 0.5
    - 1
  rand_rotate:
    range_x: 0.1
    range_y: 0.1
    range_z: 0.1
  rand_rotate90:
    spatial_axes:
    - 0
    - 1
  rand_spatial_crop_samples:
    num_samples: 8
    roi_size:
    - 96
    - 96
    - 96
  rand_zoom:
    max: 1.1
    min: 0.9
  shift_intensity:
    offsets: 0.2
  spacing:
  - 0.5
  - 0.5
  - 0.5
